### ISSUE TITLE
Firefox addon doesn't work

### ISSUE THREAD

**Issue by evpix** [follow-github-organisation/fghx#5]
The Follow button returns an error(Some problem with the operation!) and the GitHub personal access token is not saved in the settings.

**Comment by ax4** [comment]
> The Follow button returns an error(Some problem with the operation!) and the GitHub personal access token is not saved in the settings.

Hi @EvolutionPixG ! 

Could you open the developer tool of Firefox, at the page of this fghx addon settings, and check the console log for more detailed information? Thanks! 

Quote Mozillia.org's [instruction to open Dev Tools](https://developer.mozilla.org/en-US/docs/Tools): 
> You can open the Firefox Developer Tools from the menu by selecting Tools > Web Developer > Toggle Tools or use the keyboard shortcut Ctrl + Shift + I or F12 on Windows and Linux, or Cmd + Opt + I on macOS.

And I guess your issue might be related to issue #4 , where we are discussing the state of non-validation of github access token. Then we find that actually the server behind this extension / addon is not working. And @pravj replied about the expenses (or funding) problem of the server side. 

But anyway, I will volunteer to read the source code of this project, and find the possible way to fix this issue (and issue #4 also). I will reply to both threads anyway! See you.

**Comment by evpix** [comment]
@ax4 I checked the addon settings via the console and tried to save the token. Complete silence.

![2020 05 13](https://user-images.githubusercontent.com/12032252/81808514-7c9b3b80-9528-11ea-9962-089423825d82.png)

**Comment by ax4** [comment]
> @ax4 I checked the addon settings via the console and tried to save the token. Complete silence.

Hi @EvolutionPixG , thank you for providing the screenshot! I read your console.log but have no clue about what's going on after those functions are triggered. But I would take a guess that, you might just ran into the same api problem as mine. 

When I replied in the earlier comment in this issue (about 21 hours ago), I get the similar log as you, but with one extra line of error thrown. It says about the PUT method failed at calling API with code 500.  

```
settings.js:259 click on form submit
settings.js:133 add user token
settings.js:180 PUT https://api.followgithub.org/v1/user/token 500
addUserToken @ settings.js:180
(anonymous) @ settings.js:280
``` 
It looks similar to my December log, but I am not sure what's going on now.
https://github.com/follow-github-organisation/fghx/issues/4#issuecomment-568223282

I'll try to read the source code, and find the proper way of doing PUT at api. But I am not sure about @pravj how he have his server setup.

**Comment by ax4** [comment]
And as a plan B of fixing this extension, I would like to try other methods, inspired by the project [wallabag.org](http://wallabag.org/) and their [github page](https://github.com/wallabag). And many more inspirations come from project [ipfs.io](https://ipfs.io/) and the [github page](https://github.com/ipfs/ipfs)

I would like to see, how to setup a local server (as a localhost backend of this extension, or as a community-hosted backend, allowing admins to distribute their "community hosted token" to solve this problem).

Plan B means, in case of where @pravj described earlier in January, the server is not affordable, by his own funding structure. Then we should try other method to host the backend within the license of [Mozilla Public License Version 2.0](https://github.com/follow-github-organisation/fghx/blob/master/LICENSE.md).

**Comment by evpix** [comment]
@ax4 the idea is for addon [fghx](https://github.com/follow-github-organisation/fghx) to work without problems, we need it to work on the client side(not the server) in the browser. Similar to how addons works when scanning changes on pages.

Example of addons on the client side: [Update Scanner](https://github.com/sneakypete81/updatescanner) and [Web Page Scanner](https://github.com/WaldiPL/webpageScanner)

**Comment by ax4** [comment]
> @ax4 the idea is for addon [fghx](https://github.com/follow-github-organisation/fghx) to work without problems, we need it to work on the client side(not the server) in the browser. Similar to how addons works when scanning changes on pages.
> 
> 
> 
> Example of addons on the client side: [Update Scanner](https://github.com/sneakypete81/updatescanner) and [Web Page Scanner](https://github.com/WaldiPL/webpageScanner)


Thanks! I will check that out!

**Comment by EvPix** [comment]
This issue can be closed as unnecessary.
